# .github/workflows/nodejs.yml
name: Node.js Workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 22.11.0

      - run: npm ci



      - run: node index.js
